export const STORE_SEARCH_DATA_UPDATED = 'STORE_SEARCH_DATA_UPDATED';
export const STORE_SEARCH_DATA_INITIALIZED = 'STORE_SEARCH_DATA_INITIALIZED';

export const STORE_HISTORY_REMOVE = 'STORE_HISTORY_REMOVE';
export const STORE_HISTORY_ADD = 'STORE_HISTORY_ADD';
export const STORE_HISTORY_INITIALIZED = 'STORE_HISTORY_INITIALIZED';

export const STORE_FAVORITES_ADD = 'STORE_FAVORITES_ADD';
export const STORE_FAVORITES_REMOVE = 'STORE_FAVORITES_REMOVE';
export const STORE_FAVORITES_INITIALIZED = 'STORE_FAVORITES_INITIALIZED';